services:
  - type: web
    name: vura-backend
    runtime: node
    buildCommand: cd vura-backend && npm install && npx prisma generate --schema=prisma/schema.prisma && npm run build



    startCommand: cd vura-backend && npm run start:prod


    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_WEBHOOK_SECRET
        sync: false
      - key: MONNIFY_API_KEY
        sync: false
      - key: MONNIFY_SECRET_KEY
        sync: false
      - key: QOREID_CLIENT_ID
        sync: false
      - key: QOREID_SECRET
        sync: false
      - key: BUSHA_SECRET_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /api/health
